### ISSUE TITLE
Is here any code to save a graph to dortmunt dataset format

### ISSUE THREAD

**Issue by p577665228** [LeviBorodenko/dortmund2array#1]
Is here any code to save a graph to dortmunt dataset format?
The format mentioned in https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets

**Comment by LeviBorodenko** [comment]
Hi, the maintainer of the database has a script to convert graph-tools graphs. I have that script and can pass it on to you if you wish.

There is no code here to save graphs into that format.

**Comment by p577665228** [comment]
> Hi, the maintainer of the database has a script to convert graph-tools graphs. I have that script and can pass it on to you if you wish.
> 
> There is no code here to save graphs into that format.

**Comment by p577665228** [comment]
Thank you very much, please send the script to p577665228@gmail.com
I need this script to convert my graph dataset to the dortmunt dataset format.

**Comment by p577665228** [comment]
Thank you very much, please send the script to this email.

Levi Borodenko <notifications@github.com> 于2020年2月28日周五 上午9:11写道：

**Comment by LeviBorodenko** [comment]
Done.
